export enum StateFields {
    SETTINGS = 'SETTINGS',
    APP_CONFIG_GENERAL = 'APP_CONFIG_GENERAL',
    APP_CONFIG_LANGUAGE = 'APP_CONFIG_LANGUAGE',
    APP_CONFIG_USER_MENU = 'APP_CONFIG_USER_MENU',
    APP_CONFIG_THEME = 'APP_CONFIG_THEME',
}

export enum AppConfigFields {
    SIDEBAR_MENU = 'SIDEBAR_MENU',
    USER_MENU = 'USER_MENU',
    USER_MENU_OPEN = 'USER_MENU_OPEN',
}

export enum AppLanguageFields {
    LANGUAGE_MENU = 'LANGUAGE_MENU',
    LANGUAGE_MENU_OPEN = 'LANGUAGE_MENU_OPEN',
    DEFAULT_LANGUAGE = 'DEFAULT_LANGUAGE',
}

export enum AppThemeFields {
    COLOR_SCHEME = 'COLOR_SCHEME',
    THEME = 'THEME',
}
