#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '✈️ Starting the code check by eslint and prettier ✈️'

npx lint-staged ||
(
    echo '🚧 You need to fix some errors. 🚧';
    false;
)

echo '🏁 Error not found. 🏁'
